AY2223S1-CS2103T-T13-4/tp

- docs/_config.yml
Fixes #53.
Change title and repository link of Jekyll site.
> Update Jekyll Site-Wide Settings

- docs/team/seetohjinwei.md
> Add seetohjinwei PPP

- docs/UserGuide.md
Fixes #61.
1. Updated Quick Start.
2. Updated `delete` to be `contact delete` and `task delete`.
3. Removed `clear`.
> UserGuide.md: Update Quick Start, Delete Commands

- docs/UserGuide.md
> Update user guide: add tasks, bye, command summary

- docs/DeveloperGuide.md
Partially fixes #79 
- Add User Profile
- Add Value Proposition
- Add User Stories
> Update user profile, value proposition and user stories in developer guide

- docs/DeveloperGuide.md
Correcting a formatting mistake
> Update format of user guide

- docs/UserGuide.md
Changes suggested in post v1.1 meeting
> Update user guide in accordance with changes

- src/main/java/seedu/address/model/task/Task.java
- src/main/java/seedu/address/model/task/TaskList.java
- src/main/java/seedu/address/model/task/exceptions/DuplicateTaskException.java
- src/main/java/seedu/address/model/task/exceptions/TaskNotFoundException.java
Task: isSameTask() checks for similarity irrespective of isDone flag
TaskList: add() checks for similarity with isSameTask() whereas remove() checks for exact match with equals()
> Add Task and TaskList Models

- docs/DeveloperGuide.md
Changes suggested in v1.1 meeting
> Update developer guide user stories in accordance with changes

- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/TaskListCard.java
- src/main/java/seedu/address/ui/TaskListPanel.java
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/TaskListCard.fxml
- src/main/resources/view/TaskListPanel.fxml
Warning: This current iteration will cause many merge conflicts with imminent changes from Logic and Model. DO NOT MERGE!
> Add Ui Task List panel.

- src/main/java/seedu/address/logic/commands/tasks/TaskAddCommand.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/person/UniquePersonList.java
- src/test/java/seedu/address/logic/commands/ContactAddCommandTest.java
Fixes #102 
- Added TaskList as a field to AddressBook
- Each new task (containing information about Person, description, assignment, isDone) is added to this TaskList object
> Implement execute for TaskAddCommand

- src/main/java/taskbook/commons/core/Messages.java
- src/main/java/taskbook/logic/commands/tasks/TaskAddCommand.java
- src/main/java/taskbook/logic/commands/tasks/TaskDeleteCommand.java
- src/main/java/taskbook/model/AddressBook.java
- src/main/java/taskbook/model/Model.java
- src/main/java/taskbook/model/ModelManager.java
- src/main/java/taskbook/model/ReadOnlyAddressBook.java
- src/main/java/taskbook/model/task/TaskList.java
- src/test/java/taskbook/logic/commands/ContactAddCommandTest.java
- src/test/java/taskbook/model/AddressBookTest.java
- src/test/java/taskbook/model/ModelManagerTest.java
Fixes #103  
- Adds FilteredList<Task> in ModelManager
> Implement execute for TaskDeleteCommand + unit tests

- docs/UserGuide.md
Fixes #120.
For deadline tasks, using `t/` temporarily.
> Update User Guide: Task Add

- src/main/java/taskbook/model/task/Task.java
- src/main/java/taskbook/storage/JsonAdaptedTask.java
- src/main/java/taskbook/storage/JsonSerializableTaskBook.java
- src/main/java/taskbook/ui/TaskListCard.java
- src/test/java/taskbook/storage/JsonAdaptedTaskTest.java
Change task implementation to Name instead of Person
> Fb update task model

- src/main/java/taskbook/logic/commands/tasks/TaskAddCommand.java
- src/main/java/taskbook/model/task/Deadline.java
- src/main/java/taskbook/model/task/Event.java
- src/main/java/taskbook/model/task/Task.java
- src/main/java/taskbook/model/task/Todo.java
- src/main/java/taskbook/model/util/SampleDataUtil.java
- src/main/java/taskbook/storage/JsonAdaptedTask.java
- src/test/java/taskbook/testutil/TaskBuilder.java
Task subclasses:
- Todo
- Deadline
- Event
> Implement Todo, Deadline, Event classes

- src/main/resources/view/MainWindow.fxml
Size increase from 100px to 250px
> Increase size of console window size

- src/main/java/taskbook/logic/Logic.java
- src/main/java/taskbook/logic/LogicManager.java
- src/main/java/taskbook/logic/commands/tasks/TaskDeleteCommand.java
- src/main/java/taskbook/logic/commands/tasks/TaskSortAddedChronologicalCommand.java
- src/main/java/taskbook/logic/commands/tasks/TaskSortCommand.java
- src/main/java/taskbook/logic/commands/tasks/TaskSortDescriptionAlphabeticalCommand.java
- src/main/java/taskbook/logic/parser/tasks/TaskCategoryParser.java
- src/main/java/taskbook/logic/parser/tasks/TaskSortCommandParser.java
- src/main/java/taskbook/logic/parser/tasks/enums/SortTypes.java
- src/main/java/taskbook/model/Model.java
- src/main/java/taskbook/model/ModelManager.java
- src/main/java/taskbook/model/task/Description.java
- src/main/java/taskbook/model/task/Task.java
- src/main/java/taskbook/model/task/TaskList.java
- src/main/java/taskbook/ui/MainWindow.java
- src/test/java/taskbook/logic/commands/ContactAddCommandTest.java
Sorts added:
- Alphabetical Description
- Chronological Time Added
- Partially Fixes #22
> Add sort command to task list.

- build.gradle
Enable run assertions in gradle as per this week's task.
> Enable run assertions

- docs/UserGuide.md
- src/main/java/taskbook/logic/parser/CliSyntax.java
- src/main/java/taskbook/logic/parser/tasks/TaskCategoryParser.java
- src/main/java/taskbook/logic/parser/tasks/TaskSortCommandParser.java
- src/main/java/taskbook/logic/parser/tasks/enums/SortTypes.java
> Updated Task Sort command parser to match other parsers

- src/main/java/taskbook/logic/commands/tasks/TaskFindCommand.java
- src/main/java/taskbook/logic/commands/tasks/TaskSortAddedChronologicalCommand.java
- src/main/java/taskbook/logic/commands/tasks/TaskSortDescriptionAlphabeticalCommand.java
- src/main/java/taskbook/model/Model.java
- src/main/java/taskbook/model/ModelManager.java
- src/test/java/taskbook/logic/commands/ContactAddCommandTest.java
Also renamed the methods to set comparator for sorted task list
> Add methods to set predicates for filtered task list

- src/main/java/taskbook/logic/parser/tasks/TaskSortCommandParser.java
Fix a bug that causes execution of the wrong sort command
> Fix sort command parse

- docs/DeveloperGuide.md
- docs/UserGuide.md
* Add undo, redo to command summary in UG
* Update redo user story
> Fix minor problems in UG, DG

- src/main/java/taskbook/logic/parser/tasks/TaskSortCommandParser.java
- src/main/java/taskbook/model/ModelManager.java
- src/test/java/taskbook/logic/commands/TaskSortCommandTest.java
- src/test/java/taskbook/logic/commands/modelstubs/ModelStubAcceptingTaskAdded.java
- src/test/java/taskbook/logic/parser/TaskBookParserTest.java
- src/test/java/taskbook/logic/parser/TaskSortCommandParserTest.java
- src/test/java/taskbook/logic/parser/tasks/TaskCategoryParserTest.java
> Add sort unit test

- docs/UserGuide.md
- src/main/java/taskbook/logic/commands/categoryless/HelpCommand.java
- src/main/java/taskbook/logic/commands/contacts/ContactFindCommand.java
- src/main/java/taskbook/logic/commands/tasks/TaskFindCommand.java
- src/main/java/taskbook/logic/parser/contacts/ContactCategoryParser.java
- src/main/java/taskbook/logic/parser/contacts/ContactFindCommandParser.java
- src/main/java/taskbook/model/person/Person.java
- src/main/java/taskbook/model/task/Task.java
- src/test/java/taskbook/logic/commands/ContactFindCommandTest.java
- src/test/java/taskbook/logic/commands/TaskFindCommandTest.java
- src/test/java/taskbook/logic/parser/ContactFindCommandParserTest.java
- src/test/java/taskbook/logic/parser/TaskFindCommandParserTest.java
Update UG to include contact find and contact sort 
Modify command result of contact sort.
Fixes #31.
> Add contact find command

- src/main/java/taskbook/logic/commands/tasks/TaskListCommand.java
- src/test/java/taskbook/logic/commands/CommandTestUtil.java
- src/test/java/taskbook/logic/commands/TaskListCommandTest.java
> Add TaskListCommand

- src/main/java/taskbook/logic/parser/contacts/ContactFindCommandParser.java
- src/main/java/taskbook/ui/PersonListPanel.java
- src/main/java/taskbook/ui/TaskListCard.java
- src/main/java/taskbook/ui/TaskListPanel.java
- src/main/resources/view/TaskListCard.fxml
- src/main/resources/view/TaskListDeadlineCard.fxml
- src/main/resources/view/TaskListEventCard.fxml
- src/main/resources/view/TaskListTodoCard.fxml
Other updates:
Contact find command usage message bug fix
null list cells now match in colour with border
> Update Ui to show task tags

- src/main/java/taskbook/logic/parser/TaskBookParser.java
> Fix bug where non-ascii characters are not removed

- src/main/java/taskbook/commons/core/Messages.java
- src/main/java/taskbook/logic/parser/DateParser.java
- src/test/java/taskbook/logic/parser/DateParserTest.java
> Fix DateParser parsing of invalid dates

- src/main/resources/view/PersonListCard.fxml
- src/main/resources/view/TaskListCard.fxml
- src/main/resources/view/TaskListDeadlineCard.fxml
- src/main/resources/view/TaskListEventCard.fxml
- src/main/resources/view/TaskListTodoCard.fxml
> Enable line wrapping for all fields of task and contact cards

- src/main/java/taskbook/logic/commands/contacts/ContactSortCommand.java
- src/main/java/taskbook/logic/commands/tasks/TaskSortCommand.java
> Update sort usage message to include flag

- src/main/java/taskbook/logic/commands/categoryless/HelpCommand.java
- src/test/java/taskbook/logic/commands/HelpCommandTest.java
> Update help command to contain link to User Guide

- docs/AboutUs.md
- docs/_sass/minima/_base.scss
- docs/team/seetohjinwei.md
Additionally, also changed the site header from "AB-3" to "TaskBook" when printing to PDF.
> Update Jin Wei's PPP

- docs/UserGuide.md
> User Guide: Elaborate on criteria for duplicate contacts/tasks

- docs/UserGuide.md
> Fix User Guide: Specify full name 

- docs/UserGuide.md
> User Guide: Elaborate on command syntax usage (disallow multiple arguments)

- docs/UserGuide.md
> Update UG to explicitly reject country code extensions

- docs/UserGuide.md
> Update UG to be more clear about alphabetical sorting

- docs/UserGuide.md
> User Guide: Add constraints for tag

- docs/UserGuide.md
- src/main/java/taskbook/logic/commands/tasks/TaskFindCommand.java
- src/main/java/taskbook/logic/commands/tasks/TaskSortAddedChronologicalCommand.java
- src/main/java/taskbook/logic/parser/tasks/TaskFindCommandParser.java
- src/main/java/taskbook/model/Model.java
- src/main/java/taskbook/model/ModelManager.java
- src/main/java/taskbook/model/task/Description.java
- src/main/java/taskbook/model/task/Task.java
- src/main/java/taskbook/ui/TaskListCard.java
Also fixed bug where description sorting is not case sensitive. This contradicts the UG that says sorting is case sensitive. This is thus a bug that must be fixed.
However, note that since features are frozen, we will first update UG to say this sort is case insensitive, just in case. This bug is to be fixed after PE-D.
> Update code to improve code quality

- docs/UserGuide.md
- Changed wording of "index" to be more concise
- Moved "Notes" into Note segments
- Fixed wrong plurarity of "Note" and "Example"
> UG: Improve conciseness and consistency

- docs/UserGuide.md
Also changed 'Computer' to 'computer'.
> Add back to top links to ug
